import * as fs from 'fs';
import * as path from 'path';
import { Rule, RuleFinding, ScanContext } from '../types';

const SKIP_DIRS = new Set(['node_modules', '.git', 'dist']);
const MAX_FILE_SIZE = 1_000_000;

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.js', '.py', '.java', '.go', '.rb', '.rs', '.cpp', '.c', '.cs',
  '.swift', '.kt', '.php', '.sh', '.yaml', '.yml', '.json', '.xml',
  '.html', '.css', '.md', '.txt',
]);

interface PromptPattern {
  regex: RegExp;
  label: string;
}

const PROMPT_PATTERNS: PromptPattern[] = [
  { regex: /as an ai assistant/i, label: 'AI prompt artifact: "As an AI assistant"' },
  { regex: /as an ai\b/i, label: 'AI prompt artifact: "As an AI"' },
  { regex: /as a language model/i, label: 'AI prompt artifact: "As a language model"' },
  { regex: /sure,?\s+i'?d be happy to help/i, label: 'AI prompt artifact: "Sure, I\'d be happy to help"' },
  { regex: /sure,?\s+here'?s/i, label: 'AI prompt artifact: "Sure, here\'s"' },
  { regex: /certainly!\s+here'?s/i, label: 'AI prompt artifact: "Certainly! Here\'s"' },
  { regex: /i'll help you/i, label: 'AI prompt artifact: "I\'ll help you"' },
  { regex: /let me help you/i, label: 'AI prompt artifact: "Let me help you"' },
  { regex: /note:\s*this code was generated/i, label: 'AI prompt artifact: "This code was generated"' },
  { regex: /generated by\b/i, label: 'AI prompt artifact: "Generated by"' },
  { regex: /auto-generated by ai/i, label: 'AI prompt artifact: "Auto-generated by AI"' },
  { regex: /as requested/i, label: 'AI prompt artifact: "As requested"' },
  { regex: /as you asked/i, label: 'AI prompt artifact: "As you asked"' },
];

function shouldSkipFile(relativePath: string): boolean {
  const parts = relativePath.split(path.sep);
  for (const part of parts) {
    if (SKIP_DIRS.has(part)) {
      return true;
    }
  }

  const ext = path.extname(relativePath).toLowerCase();
  if (!SOURCE_EXTENSIONS.has(ext)) {
    return true;
  }

  return false;
}

function isBinaryContent(buffer: Buffer): boolean {
  const checkLength = Math.min(buffer.length, 8000);
  for (let i = 0; i < checkLength; i++) {
    if (buffer[i] === 0) {
      return true;
    }
  }
  return false;
}

function isInComment(line: string): boolean {
  const trimmed = line.trimStart();
  return (
    trimmed.startsWith('//') ||
    trimmed.startsWith('#') ||
    trimmed.startsWith('*') ||
    trimmed.startsWith('/*') ||
    trimmed.startsWith('<!--') ||
    trimmed.startsWith('"""') ||
    trimmed.startsWith("'''")
  );
}

const rule: Rule = {
  id: 'OPK-002',
  name: 'AI Prompt Artifacts',
  category: 'ai-hygiene',
  severity: 'warning',
  description: 'Detects AI prompt artifacts and conversational fragments left in source code.',
  remediation: 'Remove AI-generated conversational text from source code comments and strings.',

  async check(context: ScanContext): Promise<RuleFinding[]> {
    const findings: RuleFinding[] = [];

    for (const relativePath of context.files) {
      if (shouldSkipFile(relativePath)) {
        continue;
      }

      const absolutePath = path.join(context.rootDir, relativePath);

      let content: string | undefined;
      if (context.getFileContent) {
        content = await context.getFileContent(relativePath);
        if (content === undefined) continue;
      } else {
        let stat: fs.Stats;
        try {
          stat = fs.statSync(absolutePath);
        } catch {
          continue;
        }

        if (stat.size > MAX_FILE_SIZE || stat.size === 0) {
          continue;
        }

        let buffer: Buffer;
        try {
          buffer = fs.readFileSync(absolutePath);
        } catch {
          continue;
        }

        if (isBinaryContent(buffer)) {
          continue;
        }

        content = buffer.toString('utf-8');
      }

      const lines = content.split('\n');

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineNumber = i + 1;

        if (!isInComment(line) && !line.includes('"') && !line.includes("'") && !line.includes('`')) {
          continue;
        }

        for (const pattern of PROMPT_PATTERNS) {
          if (pattern.regex.test(line)) {
            findings.push({
              ruleId: rule.id,
              ruleName: rule.name,
              severity: rule.severity,
              message: pattern.label,
              filePath: relativePath,
              line: lineNumber,
              category: rule.category,
              remediation: rule.remediation,
            });
            break;
          }
        }
      }
    }

    return findings;
  },
};

export default rule;
